export const mockMeals = [
  {
    title: "Mediterranean Salad",
    imageUrl: "https://baconmockup.com/300/200/",
    weight: "250 gr",
    allergens: ["Nuts", "Milk"],
    price: 8.2,
    calories: 350,
    nutrition: {
      proteins: "20g",
      carbohydrates: "30g",
      fats: "10g",
    },
    soldOut: false,
  },
  {
    title: "Quinoa Bowl",
    imageUrl: "https://baconmockup.com/300/200/",
    weight: "300 gr",
    allergens: ["Soya", "Egg", "Gluten"],
    price: 9.6,
    calories: 400,
    nutrition: {
      proteins: "25g",
      carbohydrates: "35g",
      fats: "15g",
    },
    soldOut: true,
  },
  {
    title: "Vegan Burger",
    imageUrl: "https://baconmockup.com/300/200/",
    weight: "150 gr",
    allergens: ["Soya", "Sesame", "Mustard"],
    price: 7.5,
    calories: 550,
    nutrition: {
      proteins: "22g",
      carbohydrates: "40g",
      fats: "25g",
    },
    soldOut: false,
  },
  {
    title: "Chicken Caesar Salad",
    imageUrl: "https://baconmockup.com/300/200/",
    weight: "200 gr",
    allergens: ["Fish", "Celery"],
    price: 9.0,
    calories: 450,
    nutrition: {
      proteins: "30g",
      carbohydrates: "10g",
      fats: "20g",
    },
    soldOut: true,
  },
  {
    title: "Spicy Tofu Stir-Fry",
    imageUrl: "https://baconmockup.com/300/200/",
    weight: "350 gr",
    allergens: ["Soya", "Mollusc", "Lupin","Peanut",  ],
    price: 8.75,
    calories: 480,
    nutrition: {
      proteins: "26g",
      carbohydrates: "55g",
      fats: "18g",
    },
    soldOut: false,
  },
];
