export const mockMeals = [
  {
    title: "Mediterranean Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "250 gr",
    allergens: ["Nuts", "Milk"],
    price: 820,
    nutrition: [
      { name: `calories`, value: "350" },
      { name: `proteins`, value: "20g" },
      { name: `carbohydrates`, value: "30g" },
      { name: `fats`, value: "10g" },
    ],

    soldOut: false,
  },
  {
    title: "Quinoa Bowl",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "300 gr",
    allergens: ["Soya", "Egg", "Gluten"],
    price: 960,
    nutrition: [
      { name: `calories`, value: "425" },
      { name: `proteins`, value: "25g" },
      { name: `carbohydrates`, value: "35g" },
      { name: `fats`, value: "15g" },
    ],
    soldOut: true,
  },
  {
    title: "Vegan Burger",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "150 gr",
    allergens: ["Soya", "Sesame", "Mustard"],
    price: 750,
    nutrition: [
      { name: `calories`, value: "550" },
      { name: `proteins`, value: "15g" },
      { name: `carbohydrates`, value: "35g" },
      { name: `fats`, value: "10g" },
    ],
    soldOut: false,
  },
  {
    title: "Chicken Caesar Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["Fish", "Celery"],
    price: 900,
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
  {
    title: "Spicy Tofu Stir-Fry",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "350 gr",
    allergens: ["Soya", "Mollusc", "Lupin", "Peanut"],
    price: 875,
    nutrition: [
      { name: `calories`, value: "480" },
      { name: `proteins`, value: "26g" },
      { name: `carbohydrates`, value: "55g" },
      { name: `fats`, value: "18g" },
    ],
    soldOut: true,
  },
  {
    title: "Classic Caesar Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "220 gr",
    allergens: ["Eggs", "Fish", "Milk"],
    price: 750,
    nutrition: [
      { name: `calories`, value: "300" },
      { name: `proteins`, value: "15g" },
      { name: `carbohydrates`, value: "20g" },
      { name: `fats`, value: "18g" },
    ],
    soldOut: true,
  },
  {
    title: "Veggie Pasta Primavera",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "300 gr",
    allergens: ["Gluten", "Eggs"],
    price: 950,

    nutrition: [
      { name: `calories`, value: "410" },
      { name: `proteins`, value: "14g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
  {
    title: "Roasted Beet Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["Nuts"],
    price: 850,
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
  {
    title: "Spicy Black Bean Soup",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "250 gr",
    allergens: ["Celery"],
    price: 950,
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
  {
    title: "Patatas Bravas",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["None"],
    price: 650,
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
  {
    title: "Gazpacho",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "250 gr",
    allergens: ["Tomato", "Cucumber"],
    price: 700,
    calories: 150,
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: true,
  },
  {
    title: "Patatas Bravas",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["None"],
    price: 650,
    calories: 400,
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
  {
    title: "Seafood Paella",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "300 gr",
    allergens: ["Shellfish", "Fish"],
    price: 1200, // Price in cents
    nutrition: [
      { name: `calories`, value: "450" },
      { name: `proteins`, value: "30g" },
      { name: `carbohydrates`, value: "10g" },
      { name: `fats`, value: "20g" },
    ],
    soldOut: false,
  },
];
