export const mockMeals = [
  {
    title: "Mediterranean Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "250 gr",
    allergens: ["Nuts", "Milk"],
    price: 820,
    calories: 350,
    nutrition: {
      proteins: "20g",
      carbohydrates: "30g",
      fats: "10g",
    },
    soldOut: false,
  },
  {
    title: "Quinoa Bowl",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "300 gr",
    allergens: ["Soya", "Egg", "Gluten"],
    price: 960,
    calories: 400,
    nutrition: {
      proteins: "25g",
      carbohydrates: "35g",
      fats: "15g",
    },
    soldOut: true,
  },
  {
    title: "Vegan Burger",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "150 gr",
    allergens: ["Soya", "Sesame", "Mustard"],
    price: 750,
    calories: 550,
    nutrition: {
      proteins: "22g",
      carbohydrates: "40g",
      fats: "25g",
    },
    soldOut: false,
  },
  {
    title: "Chicken Caesar Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["Fish", "Celery"],
    price: 900,
    calories: 450,
    nutrition: {
      proteins: "30g",
      carbohydrates: "10g",
      fats: "20g",
    },
    soldOut: false,
  },
  {
    title: "Spicy Tofu Stir-Fry",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "350 gr",
    allergens: ["Soya", "Mollusc", "Lupin", "Peanut"],
    price: 875,
    calories: 480,
    nutrition: {
      proteins: "26g",
      carbohydrates: "55g",
      fats: "18g",
    },
    soldOut: true,
  },
  {
    title: "Classic Caesar Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "220 gr",
    allergens: ["Eggs", "Fish", "Milk"],
    price: 750,
    calories: 300,
    nutrition: {
      proteins: "15g",
      carbohydrates: "20g",
      fats: "18g",
    },
    soldOut: true,
  },
  {
    title: "Veggie Pasta Primavera",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "300 gr",
    allergens: ["Gluten", "Eggs"],
    price: 950,
    calories: 410,
    nutrition: {
      proteins: "14g",
      carbohydrates: "58g",
      fats: "12g",
    },
    soldOut: false,
  },
  {
    title: "Roasted Beet Salad",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["Nuts"],
    price: 850,
    calories: 250,
    nutrition: {
      proteins: "6g",
      carbohydrates: "24g",
      fats: "15g",
    },
    soldOut: false,
  },
  {
    title: "Spicy Black Bean Soup",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "250 gr",
    allergens: ["Celery"],
    price: 950,
    calories: 300,
    nutrition: {
      proteins: "18g",
      carbohydrates: "45g",
      fats: "5g",
    },
    soldOut: false,
  },
  {
    title: "Patatas Bravas",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["None"],
    price: 650,
    calories: 400,
    nutrition: {
      proteins: "5g",
      carbohydrates: "60g",
      fats: "20g",
    },
    soldOut: false,
  },
  {
    title: "Gazpacho",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "250 gr",
    allergens: ["Tomato", "Cucumber"],
    price: 700,
    calories: 150,
    nutrition: {
      proteins: "4g",
      carbohydrates: "18g",
      fats: "5g",
    },
    soldOut: true,
  },
  {
    title: "Patatas Bravas",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "200 gr",
    allergens: ["None"],
    price: 650,
    calories: 400,
    nutrition: {
      proteins: "5g",
      carbohydrates: "60g",
      fats: "20g",
    },
    soldOut: false,
  },
  {
    title: "Seafood Paella",
    imageUrl: "https://baconmockup.com/420/340/",
    weight: "300 gr",
    allergens: ["Shellfish", "Fish"],
    price: 1200, // Price in cents
    calories: 520,
    nutrition: {
      proteins: "25g",
      carbohydrates: "72g",
      fats: "12g",
    },
    soldOut: false,
  },
];
